lib/betting_system_web/router.ex
defmodule BettingSystemWeb.Router do
  use BettingSystemWeb, :router

  import BettingSystemWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BettingSystemWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BettingSystemWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BettingSystemWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BettingSystemWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", BettingSystemWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create

    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create

    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BettingSystemWeb do
    pipe_through [:browser, :require_authenticated_admins]

    live "/sports", SportLive.Index, :index
    live "/simulate", SimulategamesLive.Index, :index

    live "/sports/new", SportLive.Index, :new
    live "/sports/:id/edit", SportLive.Index, :edit

    # live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id/edit", UserLive.Index, :edit
    live "/us/:id", UserLive.Show, :show

    live "/users/:id/view_user", UserLive.Index, :view_user

    live "/sports/:id", SportLive.Show, :show
    live "/sports/:id/show/edit", SportLive.Show, :edit
    # live "/games", GameLive.Index, :index
    live "/games/new", GameLive.Index, :new
    live "/games/:id/edit", GameLive.Index, :edit

    live "/games/completed", GameLive.Completed, :index

    live "/games/:id", GameLive.Show, :show
    live "/games/:id/show/edit", GameLive.Show, :edit

    live "/user/bets/:id", BetsLive.Index, :index
    live "/user/bets_history/", UserHistoryLive.Index, :index

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", BettingSystemWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/users", UserLive.Index, :index
    live "/games", GameLive.Index, :index
  end

  scope "/", BettingSystemWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/betting_system_web/views/layout_view.ex
defmodule BettingSystemWeb.LayoutView do
  use BettingSystemWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/betting_system_web/templates/layout/_user_menu.html.heex
<ul>
  <%= if @current_user do %>
    <button class="bg-red-500">
      <%= link("Settings", to: Routes.user_settings_path(@conn, :edit)) %>
    </button>
    <li><%= link("Log out", to: Routes.user_session_path(@conn, :delete), method: :delete) %></li>
  <% else %>
    <button><%= link("Register", to: Routes.user_registration_path(@conn, :new)) %></button>
    <li><%= link("Log in", to: Routes.user_session_path(@conn, :new)) %></li>
  <% end %>
</ul>

lib/betting_system_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/betting_system_web/templates/layout/gamelive.html.heex
<nav class="flex justify-between bg-[#202A39]  text-white p-[30px]">
  <%= if @flash["info"] do %>
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>
  <div class="">
    <p class="text-xl font-semibold poppins-bold">Spor00000000tOdds</p>
  </div>
  <div class="poppins-light">
    <a class="m-2 border-b border-transparent  hover:border-white" href="#">live</a>
    <a class="m-2 border-b border-transparent  hover:border-white" href="#">betting</a>

    <a class="m-2 border-b border-transparent  hover:border-white" href="#">casion</a>

    <a class="m-2 border-b border-transparent  hover:border-white" href="#">lucky Drops</a>

    <a class="m-2 border-b border-transparent  hover:border-white" href="#">live casino</a>
    <a class="m-2 border-b border-transparent  hover:border-white" href="#">
      live promotions
    </a>
  </div>

  <div>settings</div>
</nav>

<div class="bg-[#161F2C] flex justify-evenly poppins-light text-white  p-2">
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2"><%= FontAwesome.icon("house", type: "solid", class: "h-4 w-4") %></div>
    <div>home</div>
  </div>
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2">
      <%= FontAwesome.icon("tower-broadcast", type: "solid", class: "h-4 w-4") %>
    </div>
    <div>live</div>
  </div>
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2">
      <%= FontAwesome.icon("calendar", type: "regular", class: "h-4 w-4") %>
    </div>
    <div>Today</div>
  </div>
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2">
      <%= FontAwesome.icon("futbol", type: "regular", class: "h-4 w-4") %>
    </div>
    <div>football</div>
  </div>
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2">
      <%= FontAwesome.icon("basketball", type: "solid", class: "h-4 w-4") %>
    </div>
    <div>baskteball</div>
  </div>
  <div class="flex flex-col bg-[#202A39] items-center justify-center w-[12%] rounded h-[70px]">
    <div class="ml-2">
      <%= FontAwesome.icon("football", type: "solid", class: "h-4 w-4") %>
    </div>
    <div>Rugby</div>
  </div>
</div>

lib/betting_system_web/templates/layout/live.html.heex
<main>
  <%= if @flash["info"] do %>
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= live_flash(@flash, :info) %>
    </p>
  <% end %>

  <%= if @flash["error"] do %>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <%= live_flash(@flash, :error) %>
    </p>
  <% end %>

  <nav class="flex md:justify-between bg-[#202A39]  text-white p-4 md:p-[30px]">
    <div class="">
      <p class=" text-sm md:text-xl font-semibold poppins-bold">SportOdds</p>
    </div>
    <div class="invisible md:visible text-sm md:text-base poppins-light">
      <a class="m-2 border-b border-transparent  hover:border-white" href="#">live</a>
      <a class="m-2 border-b border-transparent  hover:border-white" href="#">betting</a>

      <a class="m-2 border-b border-transparent  hover:border-white" href="#">casion</a>

      <a class="m-2 border-b border-transparent  hover:border-white" href="#">lucky Drops</a>

      <a class="m-2 border-b border-transparent  hover:border-white" href="#">live casino</a>
      <a class="m-2 border-b border-transparent  hover:border-white" href="#">
        live promotions
      </a>
    </div>

    <div>
      <div class="drop-button hover:cursor-pointer flex gap-2" onclick="toggle()">
        <div>
          <%= Heroicons.icon("user-circle",
            type: "outline",
            class: "h-6 w-6 border-[1px] border-green-500 rounded-full m-[-2px]"
          ) %>
        </div>
        <div class="flex items-center justify-center">
          <%= Heroicons.icon("chevron-down", type: "outline", class: "h-6 w-6 ") %>
        </div>
      </div>
    </div>
  </nav>
  <div
    id="myDropdown"
    class="dropdownlist flex flex-col gap-2 p-2 absolute bg-gray-800 w-[200px] invisible text-white top-[75px] right-0 mt-3 poppins-light overflow-auto z-30 "
  >
    <%= link( to: Routes.user_index_path(@socket, :index)) do %>
      <div class="flex gap-2">
        <%= Heroicons.icon("user", type: "outline", class: "h-6 w-6") %>
        <span class="align-top">profile</span>
      </div>
    <% end %>

    <%= link( to: Routes.user_session_path(@socket, :delete), method: :delete) do %>
      <div class="flex gap-2">
        <%= Heroicons.icon("arrow-left-on-rectangle", type: "outline", class: "h-6 w-6") %>
        <span class="align-top">log out</span>
      </div>
    <% end %>
  </div>

  <div class="bg-[#161F2C] flex justify-between md:justify-evenly poppins-light text-white  p-2">
    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[50px] md:w-[12%] rounded h-[70px]">
      <div class="ml-2"><%= FontAwesome.icon("house", type: "solid", class: "h-4 w-4") %></div>
      <div class="text-xs">home</div>
    </div>

    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[50px] md:w-[12%] rounded h-[70px]">
      <div class="ml-2">
        <%= FontAwesome.icon("tower-broadcast", type: "solid", class: "h-4 w-4") %>
      </div>
      <div class="text-xs">live</div>
    </div>
    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[50px] md:w-[12%] rounded h-[70px]">
      <div class="ml-2">
        <%= FontAwesome.icon("calendar", type: "regular", class: "h-4 w-4") %>
      </div>
      <div class=" text-xs">Today</div>
    </div>
    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[50px] md:w-[12%] rounded h-[70px]">
      <div class="ml-2">
        <%= FontAwesome.icon("futbol", type: "regular", class: "h-4 w-4") %>
      </div>
      <div class="text-xs">football</div>
    </div>
    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[55px] md:w-[12%]  rounded h-[70px]">
      <div class="ml-2">
        <%= FontAwesome.icon("basketball", type: "solid", class: "h-4 w-4") %>
      </div>
      <div class=" text-xs">baskteball</div>
    </div>
    <div class="flex flex-col bg-[#202A39] items-center justify-center w-[50px] md:w-[12%] rounded h-[70px]">
      <div class="ml-2">
        <%= FontAwesome.icon("football", type: "solid", class: "h-4 w-4") %>
      </div>
      <div class="text-xs">Rugby</div>
    </div>
  </div>
  <div
    class="absolute   pt-[180px] top-[30px] left-[0px] bottom-[0px] md:w-[300px] h-[100%]"
    style=" 
    z-index:4;"
  >
    <div class="flex flex-col  ">
      <%= if @user.role == "Admin" ||  @user.role == "SuperAdmin" do %>
        <div
          id="menu"
          style="z-index:4; "
          class="hidden  md:contents w-auto h-auto flex-col border border-gray-700 bg-[#141C33] md:bg-[#060C1F] rounded   "
        >
          <div class="md:hidden flex justify-between p-2 m-2" onclick="closeside()">
            <div></div>
            <span class="poppins-bold text-2xl text-[#8A92AB]">
              X
            </span>
          </div>

          <div class=" m-[20px] p-[20px]  text-[#8A92AB]">
            <span>
              <%= live_redirect(" sports", to: Routes.sport_index_path(@socket, :index)) %>
            </span>
          </div>
          <div class=" m-[20px] p-[20px]  text-[#8A92AB]">
            <span>
              <%= live_redirect(" Games", to: Routes.game_index_path(@socket, :index)) %>
            </span>
          </div>
          <div class=" m-[20px] p-[20px]  text-[#8A92AB]">
            <span>
              <%= live_redirect(" simulate games",
                to: Routes.simulategames_index_path(@socket, :index)
              ) %>
            </span>
          </div>
          <div class=" m-[20px] p-[20px]  text-[#8A92AB]">
            <span>
              <%= live_redirect(" system users", to: Routes.user_index_path(@socket, :index)) %>
            </span>
          </div>
          <div class=" m-[20px] p-[20px]  text-[#8A92AB]">
            <span>
              <%= live_redirect(" my profile", to: Routes.user_index_path(@socket, :index)) %>
            </span>
          </div>
        </div>
      <% else %>
        <div class="hidden md:contents">
          <div class="mb-2">
            <div class="mx-[20px]  bg-[#202a39] h-[50px] p-2 ">
              <span class="poppins-regular  text-white">
                Popular Events
              </span>
            </div>
            <div
              style=" border-color:rgba(123,131,156,.6); "
              class="flex mx-[20px] border-b-[1px] border-t-[1px]   bg-[#141c33]"
            >
              <div class="w-[25%]  ">
                <img
                  src="/images/WC_no_background.png"
                  alt="scadvert logo"
                  class="object-scale-down h-[90%] w-[90%]  "
                />
              </div>
              <div class="poppins-regular  text-white">
                World Cup 2022
              </div>
            </div>
            <div
              style=" padding:2px; border-color:rgba(123,131,156,.6); "
              class="flex mx-[20px] border-b-[1px] border-t-[1px]  bg-[#141c33]"
            >
              <div class="w-[25%]">
                <img
                  src="/images/champe_no_bc.png"
                  alt="scadvert logo"
                  class="object-scale-down h-[90%] w-[90%]  "
                />
              </div>
              <div class="poppins-regular  text-white">
                Champions League
              </div>
            </div>
          </div>

          <div
            style=" padding:2px; border-color:rgba(123,131,156,.6);  "
            class="flex mx-[20px] border-b-[1px] border-t-[1px]  mb-[20px] bg-[#141c33]"
          >
            <div class="w-[25%]">
              <img
                src="/images/c.png"
                alt="scadvert logo"
                class="object-scale-down h-[90%] w-[90%]  "
              />
            </div>
            <div class="poppins-regular  text-white">
              Favourites
            </div>
          </div>
          <div class="mb-2">
            <div class="mx-[20px] flex items-center  justify-around bg-[#202a39] h-[50px] ">
              <span class="poppins-regular text-white">
                live
              </span>
              <span class="poppins-regular text-white">
                prematch
              </span>
            </div>
            <div
              style=" border-color:rgba(123,131,156,.6); "
              class="flex mx-[20px] border-b-[1px] border-t-[1px]   bg-[#141c33]"
            >
              <div class="w-[25%]  ">
                <img
                  src="/images/WC_no_background.png"
                  alt="scadvert logo"
                  class="object-scale-down h-[90%] w-[90%]  "
                />
              </div>
              <div class="poppins-regular  text-white">
                World Cup 2022
              </div>
            </div>
            <div
              style=" padding:2px; border-color:rgba(123,131,156,.6); "
              class="flex mx-[20px] border-b-[1px] border-t-[1px]  bg-[#141c33]"
            >
              <div class="w-[25%]">
                <img
                  src="/images/champe_no_bc.png"
                  alt="scadvert logo"
                  class="object-scale-down h-[90%] w-[90%]  "
                />
              </div>
              <div class="poppins-regular  text-white">
                Champions League
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= if @user.role == "Admin" ||  @user.role == "SuperAdmin" do %>
    <div class="md:pl-[200px]">
      <%= @inner_content %>
    </div>
  <% else %>
    <div class="md:pl-[305px]">
      <%= @inner_content %>
    </div>
  <% end %>
  <script>
      function toggle(){
        console.log("dropdown");
        element = document.getElementById("myDropdown").classList.toggle("invisible");
      }
      document.addEventListener("click", function(event) {
                  var dropdown = document.querySelector(".dropdownlist");
                  var dropButton = document.querySelector(".drop-button");

                  if (dropdown && !dropdown.contains(event.target) && !dropButton.contains(event.target)) {
                          if (!dropdown.classList.contains('invisible')) {
                          dropdown.classList.add('invisible');
              }
      }
    });
  </script>
</main>

lib/betting_system_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag(assigns[:page_title] || "BettingSystem", suffix: " · Phoenix Framework") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
    </script>
    <script src="https://cdn.jsdelivr.net/momentjs/2.14.1/moment.min.js">
    </script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.js



"
    >
    </script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/themes/dark.css"
    />

    <style>
                     .glow {
                    font-size: 70px;
                    color: #ffffff;
                    text-align: center;
                    text-shadow: 0 0 10px #eeeeee, 0 0 20px #000000, 0 0 30px #000000, 0 0 40px #000000, 
                                 0 0 50px #4da6ff, 0 0 60px #4da6ff, 0 0 70px #4da6ff;
                  }
                      ::-webkit-scrollbar {
              width: 7px; /* Set the width of the scrollbar */
            }

            ::-webkit-scrollbar-thumb {
              background-color: #141C33; /* Set the color of the thumb */
            }
            .translate-x-0 {
        transform: translateX(0); /* Move the sidebar in from the left */
      }
                
          
    </style>
  </head>
  <body class="bg-[#060C1F] relative">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flatpickr/4.2.3/flatpickr.js">
    </script>

    <%= @inner_content %>
  </body>
</html>